export const weeklyColumnDefs = [
  { key: "production_order_no", title: "生产订单号" },
  { key: "customer_remark", title: "客户备注" },
  { key: "product_name", title: "产品名称" },
  { key: "spec_model", title: "规格型号" },
  { key: "production_batch_no", title: "生产批号" },
  { key: "order_qty", title: "订单数量" },
  { key: "packaging_form", title: "包装形式" },
  { key: "sales_order_no", title: "销售订单号" },
  { key: "workshop_outer_packaging_date", title: "车间外包装日期" },
  { key: "process_schedule_remark", title: "备注(工序排产)" },
];

export const monthlyColumnDefs = [
  { key: "order_date", title: "下单日期" },
  { key: "production_order_no", title: "生产订单号" },
  { key: "customer_remark", title: "客户备注" },
  { key: "product_name", title: "产品名称" },
  { key: "spec_model", title: "规格型号" },
  { key: "production_batch_no", title: "生产批号" },
  { key: "planned_finish_date_2", title: "计划完工日期2" },
  { key: "production_date_foreign_trade", title: "生产日期（外贸）" },
  { key: "order_qty", title: "订单数量" },
  { key: "packaging_form", title: "包装形式" },
  { key: "sales_order_no", title: "销售订单号" },
  { key: "purchase_due_date", title: "采购交期" },
  { key: "injection_due_date", title: "注塑交期" },
  { key: "market_remark_info", title: "市场备注信息" },
  { key: "market_demand", title: "市场需求" },
  { key: "planned_finish_date_1", title: "计划完工日期1" },
  { key: "semi_finished_code", title: "半成品代码" },
  { key: "semi_finished_inventory", title: "半成品库存" },
  { key: "semi_finished_demand", title: "半成品需求" },
  { key: "semi_finished_wip", title: "半成品在制" },
  { key: "need_order_qty", title: "需下单量" },
  { key: "pending_inbound_qty", title: "待入库量" },
  { key: "weekly_monthly_process_plan", title: "周度/月度计划(工序排产)" },
  { key: "workshop_outer_packaging_date", title: "车间外包装日期" },
  { key: "note", title: "备注" },
  { key: "workshop_completed_qty", title: "完工数量(车间)" },
  { key: "workshop_completed_time", title: "完工时间（车间）" },
  { key: "outer_completed_qty", title: "完工数量（外协）" },
  { key: "outer_completed_time", title: "完工时间（外协）" },
  { key: "match_status", title: "匹配状态" },
];

export const monthlyGroups = [
  { title: "订单基本信息", span: 14 },
  { title: "市场需求", span: 2 },
  { title: "半成品信息", span: 6 },
  { title: "订单排产信息", span: 3 },
  { title: "订单进度", span: 4 },
  { title: "匹配", span: 1 },
];

export const sharedFieldPairs = [
  ["customer_remark", "customer_remark", "客户备注"],
  ["product_name", "product_name", "产品名称"],
  ["spec_model", "spec_model", "规格型号"],
  ["production_batch_no", "production_batch_no", "生产批号"],
  ["order_qty", "order_qty", "订单数量"],
  ["packaging_form", "packaging_form", "包装形式"],
  ["sales_order_no", "sales_order_no", "销售订单号"],
  ["workshop_outer_packaging_date", "workshop_outer_packaging_date", "车间外包装日期"],
];
